honey:
 image: honeynet/conpot

tor-hs:
 build: hidden-service
 links:
  - honey
 external_links:
  - bro_bro-xinitd_1:bro
 expose:
  - 80

 volumes:
 # - "./volumes/tor/hidden_service:/var/lib/tor/hidden_service" 
  - "./volumes/tor/etc:/etc/tor"
 
