version: '2'
services:
 ssh:
  image: danielguerra/docker-dind-sshd
  hostname: ssh
  privileged: true
  ports:
   - "4848:22"
  volumes:
   - ssh-data:/root/showcase/
   - ssh-keys:/root/.ssh/

volumes:
 ssh-keys:
 ssh-data:
