version: '2'
services:
 https:
  image: steveltn/https-portal
  ports:
    - "80:80"
    - "443:443"
  restart: always
  volumes:
 # - ./volumes/https/comodo:/var/lib/https-portal/
   - ./volumes/https/comodo:/var/www/vhosts/nodered.93.191.128.252.dns.uk.ms
   - ./volumes/https/keys:/var/lib/https-portal/nodered.93.191.128.252.dns.uk.ms/local/
  environment:
   - STAGE=local
   #- STAGE=production
   - WEBSOCKET=true
   - DOMAINS=nodered.${SHOWCASE_IP_ADDRESS}.dns.uk.ms
  networks:
   mynet:
    ipv4_address: 172.25.0.8

 dns:
  build: dns
  ports:
   - 53:53/udp

