version: '2'
services:
 nodered:
  extends:
   file: docker-compose/docker-compose-ttn-test.yml
   service: nodered
  environment:
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_MARCEL}
  networks:
   mynet:
    ipv4_address: 172.25.0.8

 zeppelin:
  image: dylanmei/zeppelin
  ports:
   - "8080:8080"
