version: '2'
services:
 nodered:
  extends:
   file: docker-compose/docker-compose-ttn-test.yml
   service: nodered
  environment:
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_MARCEL}
  networks:
   mynet:
    ipv4_address: 172.25.0.8
  logging:
   driver: "gelf"
   options:
    gelf-address: "udp://172.25.0.100:12201"
