version: '2'

services:
 kali:
  image: marcelmaatkamp/kali
  command: ./start.sh
  environment:
   - AMQP_HOSTNAME=stein.pirod.nl
   - AMQP_USERNAME=wifi.probes
   - AMQP_PASSWORD=wifi.probes
   - LOCATION_NAME="kamer marcel en ab"
   - LOCATION_LAT=52.05333 
   - LOCATION_LON=5.28056
  privileged: true
  network_mode: "host"

