elasticsearch:
  image: elasticsearch:latest
  # build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash
  # privileged: true
  # command: /opt/logstash/bin/logstash -e 'input { syslog { port => 514 } } output { stdout { } }'
  command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./volumes/logstash:/etc/logstash/conf.d
  expose:
    - 514/udp
    - 5514/udp
    - 5515
    - 5515/udp
  ports:
    - 514:5514/udp
    - 515:5515
    - 515:5515/udp

kibana:
  build: kibana/
  volumes:
    - ./volumes/kibana/:/opt/kibana/config
  ports:
    - "5601:5601"
  links:
    - elasticsearch

rabbitmq:
 build: rabbitmq
 ports: 
  - "15672:15672"

fluentd:
  build: ./fluentd
  privileged: true
  links:
   - "elasticsearch"
  ports:
   - "22422:22422"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /var/lib/docker:/var/lib/docker 
   - ./volumes/fluentd/var/run:/var/run
   - ./volumes/fluentd/var/log/docker:/var/log/docker

