version: '2'
services:
 mysql:
  volumes:
   - ./volumes/mysql:/var/lib/mysql/
   - ./mysql:/docker-entrypoint-initdb.d/
 nodered:
  environment:
   - SHOWCASE_MQTT_USER=70B3D57ED0000105
   - SHOWCASE_MQTT_PASSWORD=YDKlDg0sjC2CP/DzhH4Hls9ChpM+Bi3eDi60r/A8oaM=
   - SHOWCASE_TELEGRAM_TOKEN=257187787:AAH6ukcTh17o8TfWmLdmAV3MkAcmwHElS90