version: '2'
services:
 nodered:
  environment:
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_ACC}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_ACC}
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_TEST}
