version: '2'

services:

 docker-ui:
  image: uifd/ui-for-docker
  restart: always
  privileged: true
#  ports:
#   - 9000:9000
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock

 rabbitmq:
  image: marcelmaatkamp/rabbitmq-mqtt-ldap
  restart: always
  hostname: rabbitmq
#  ports:
#   - 15672:15672
  environment:
    RABBITMQ_NODENAME: rabbitmq@rabbitmq
  volumes:
   - ./volumes/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia

 mysql:
  image: mysql
  restart: always
  hostname: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - ./volumes/mysql:/var/lib/mysql/
   - ./mysql:/docker-entrypoint-initdb.d/

 nodered:
  build: raptor-node-red
  restart: always
  hostname: nodered
  depends_on:
   - rabbitmq
   - mysql
  links:
   - rabbitmq:rabbitmq
   - mysql:mysql
  ports:
   - 1880:1880
  volumes:
   - ./volumes/nodered:/node-red-data/
  # environment:
  #  - SHOWCASE_MQTT_USER=70B3D57ED0000B7E
  #  - SHOWCASE_MQTT_PASSWORD=tsCycz92q6xhIeHCRjWhD38XjHBOz5uZUJ7y9hSmfRA=
  #  - SHOWCASE_TELEGRAM_TOKEN=221611837:AAGCjDOlCF0kGKvh3TdgyimaeZAhbT2EXu8

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  hostname: phpmyadmin
# ports:
#  - 8080:80
  depends_on:
   - mysql
  links:
   - mysql:db
  volumes:
   - ./volumes/phpmyadmin:/sessions

 phreeze:
  image: marcelmaatkamp/phreeze
  links:
   - mysql:mysql
  depends_on:
   - mysql
  volumes:
   - ./volumes/phreeze/showcase:/var/www/html/showcase
#  ports:
#   - 80:80

volumes:
 nexus3:
