version: '2'
services:
 nodered:
  environment:
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_TEST}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_TEST}
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_MARCEL}

 zeppelin:
  image: dylanmei/zeppelin
  ports:
   - "8080:8080"
