version: '2'

services:
 nodered:
  volumes:
   - ./raptor-node-red:/node-red
  environment:
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_TEST}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_TEST}
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_AB}

 rabbitmq:
  ports:
   - 15672:15672

 phpmyadmin:
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  ports:
   - 81:80

 phreeze:
  ports:
   - 82:80

# Definieer test image om integration tests via RabbitMQ uit te kunnen voeren
#  test:
#   build: test
#   hostname: test
#   depends_on:
#    - rabbitmq
#    - mysql
#    - nodered
#   links:
#    - rabbitmq:rabbitmq
#    - mysql:mysql
#   ports:
#    - 5858:5858
#   volumes:
#    - ./test:/src
#   networks:
#    mynet:
#     ipv4_address: 172.25.0.8

# Nodejs backend als vervanging voor node-red
 backend:
  build: backend-nodejs
  hostname: backend
  depends_on:
   - rabbitmq
   - mysql
  links:
   - rabbitmq:rabbitmq
   - mysql:mysql
  ports:
   - 5858:5858
  volumes:
   - ./backend-nodejs:/src
  environment:
   - DEVELOP=1
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_ACC}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_ACC}
  networks:
   mynet:
    ipv4_address: 172.25.0.8
