version: '2'
services:
 nodered:
  environment:
   - SHOWCASE_MQTT_USER=70B3D57ED0000105
   - SHOWCASE_MQTT_PASSWORD=YDKlDg0sjC2CP/DzhH4Hls9ChpM+Bi3eDi60r/A8oaM=
   - SHOWCASE_TELEGRAM_TOKEN=292441232:AAHS3zE8dyJWRUCx29bLx-MOwWEpimRt0mk
