version: '2'

services:
 nodered:
  volumes:
   - ./raptor-node-red:/node-red
  environment:
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_TEST}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_TEST}
   - SHOWCASE_TELEGRAM_TOKEN=${SHOWCASE_TELEGRAM_BOT_AB}

 rabbitmq:
  ports:
   - 15672:15672

 phpmyadmin:
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  ports:
   - 81:80

 phreeze:
  ports:
   - 82:80

# Nodejs backend als vervanging voor node-red
backend:
  ports:
   - 5858:5858
  environment:
  # What kind of environment:
  # DEVELOP=0 # autostart processMessages
   - DEVELOP=1 # keep docker image alive for development environment
  #  Alle environment variabelen met hun default waarden
  # graylog2 logging
  # - SHOWCASE_GRAYLOG=0
  # - SHOWCASE_GRAYLOG_HOST=graylog
  # - SHOWCASE_GRAYLOG_PORT=12201
  # - SHOWCASE_GRAYLOG_LEVEL=debug
  # console logging
  # - SHOWCASE_LOG_LEVEL=info
  # - SHOWCASE_LOG_META=0
  # mysql server settings
  # - SHOWCASE_MYSQL_HOST=mysql
  # - SHOWCASE_MYSQL_USER=root
  # - SHOWCASE_MYSQL_PASSWORD=my-secret-pw
  # - SHOWCASE_MYSQL_DATABASE=SHOWCASE_GRAYLOG
  # TTN mqtt settings
  # - SHOWCASE_MQTT_SERVER=staging.thethingsnetwork.org
  # - SHOWCASE_MQTT_PORT=1883
   - SHOWCASE_MQTT_USER=${SHOWCASE_TTN_USERNAME_ACC}
   - SHOWCASE_MQTT_PASSWORD=${SHOWCASE_TTN_PASSWORD_ACC}
  # RabbitMQ amqp settings
  # - SHOWCASE_AMQP_SERVER=rabbitmq
  # - SHOWCASE_AMQP_PORT=5672
  # - SHOWCASE_AMQP_USER=guest
  # - SHOWCASE_AMQP_PASSWORD=guest
  # - SHOWCASE_AMQP_QUEUE_SUFFIX=nodejs_queue_
  # RabbitMQ default message processing in and out settings
  # - SHOWCASE_AMQP_TTN_EXCHANGE_OUT=showcase.ttn_message
  # - SHOWCASE_AMQP_KPN_EXCHANGE_IN=showcase.kpn_message
  # - SHOWCASE_AMQP_KPN_EXCHANGE_OUT # defaults to SHOWCASE_AMQP_TTN_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_DECODE_EXCHANGE_IN # defaults to SHOWCASE_AMQP_TTN_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_DECODE_EXCHANGE_OUT=showcase.observation
  # - SHOWCASE_AMQP_OBSERVATION_LOG_EXCHANGE_IN # defaults to SHOWCASE_AMQP_DECODE_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_OBSERVATION_LOG_EXCHANGE_OUT=showcase.logged_observation
  # - SHOWCASE_AMQP_ALERT_EXCHANGE_IN # defaults to SHOWCASE_AMQP_OBSERVATION_LOG_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_ALERT_EXCHANGE_OUT=showcase.alert"
  # - SHOWCASE_AMQP_ALERT_LOG_EXCHANGE_IN # defaults SHOWCASE_AMQP_ALERT_EXCHANGE_OUT
  # - SHOWCASE_AMQP_ALERT_LOG_EXCHANGE_OUT=showcase.notification
  # - SHOWCASE_AMQP_NOTIFICATION_EXCHANGE_IN # defaults to SHOWCASE_AMQP_ALERT_LOG_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_NOTIFICATION_EXCHANGE_OUT=showcase.logged_notification
  # - SHOWCASE_AMQP_SLACK_EXCHANGE_IN # defaults to SHOWCASE_AMQP_NOTIFICATION_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_SLACK_EXCHANGE_OUT=showcase.notification_sent_slack
  # - SHOWCASE_AMQP_TELKEGRAM_EXCHANGE_IN # defaults to SHOWCASE_AMQP_NOTIFICATION_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_TELEGRAM_EXCHANGE_OUT=showcase.notification_sent_telegram
  # - SHOWCASE_AMQP_SMS_EXCHANGE_IN # defaults to SHOWCASE_AMQP_NOTIFICATION_EXCHANGE_OUT value
  # - SHOWCASE_AMQP_SMS_EXCHANGE_OUT=showcase.notification_sent_sms
  # Slack settings
  # - SHOWCASE_SLACK_HOOK_URL=https://hooks.slack.com/services/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
  # Telegram settings
  # - SHOWCASE_TELEGRAM_TOKEN=292441232:AAHS3zE8dyJWRUCx29bLx-MOwWEpimRt0mk
  # - SHOWCASE_TELEGRAM_CHAT_ID=-1001097331998 # default chatid, if no chatid is defined in parameter p1
  # Sms (twilio) settings
  # - SHOWCASE_TWILIO_SID=AC600a293801150c7c3af3a5747a3ba4ae
  # - SHOWCASE_TWILIO_TOKEN=ad1f82c56f5b9f048e72558ae984edf8
  # - SHOWCASE_TWILIO_FROM_PHONE=+19787124065

# Definieer test image om integration tests via RabbitMQ uit te kunnen voeren
# alleen voor amqp based integratie tests
#  test:
#   build: test
#   hostname: test
#   depends_on:
#    - rabbitmq
#    - mysql
#    - nodered
#   links:
#    - rabbitmq:rabbitmq
#    - mysql:mysql
#   ports:
#    - 5858:5858
#   volumes:
#    - ./test:/src
#   networks:
#    mynet:
#     ipv4_address: 172.25.0.8
