# http://opendj.forgerock.org/doc/admin-guide/
opendj:
 image: forgerock/opendj
 volumes:
  - ./volumes/forgerock/opendj:/opt/opendj/instances/instance1
 expose:
  - 389
  - 636
  - 4444

# http://docker:8090/openam
# https://wikis.forgerock.org/confluence/display/openam/Deploy+OpenAM
# https://github.com/ForgeRock/docker/blob/master/openam-nightly/Dockerfile
# dc=openam,dc=forgerock,dc=org
openam:
  # image: wstrange/openam-nightly
  image: forgerock/openam
  ports:
    - 8090:8080
    - 8091:8081
    - 8092:8082
  volumes:
    - ./volumes/forgerock/openam:/root/openam
  extra_hosts:
    - "openam.example.com:192.168.56.11"
    - "openam:192.168.56.11"
  links:
    - opendj

# https://github.com/ForgeRock/docker/tree/master/openidm-nightly
# http://docker:8095/
openidm:
  image: wstrange/openidm-nightly
  ports:
    - "8095:8080"