rtorrent:
 image: diameter/rtorrent-rutorrent:64-latest
 ports:
  - "8081:80"
  - "8442:443"
  - "49160:49160"
  - "49161:49161"
 volumes: 
  - "./volumes/rtorrent/downloads:/downloads"

airvideohd:
 image: dmaxwell/airvideohd
 ports:
  - "45633:45633/tcp"
 volumes:
  - "./volumes/airvideohd/config:/config"
  - "./volumes/airvideohd/temp:/conversionPath"
  - "./volumes/rtorrent/downloads:/videos"

