haproxy:
 build: haproxy/
 links:
  - rabbit1
  - rabbit2
  - rabbit3

rabbit1:
  build: rabbit1/
  hostname: rabbit1
  ports:
   - "5672:5672"
   - "15672:15672"

rabbit2:
  build: rabbit2/
  hostname: rabbit2
  links:
   - rabbit1
  environment: 
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
   - "5673:5672"
   - "15673:15672"

rabbit3:
  build: rabbit3/
  hostname: rabbit3
  links:
   - rabbit1
   - rabbit2
  environment: 
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1   
  ports:
   - "5674:5672"
